### ISSUE TITLE
Allow logged-in users to add a class section's office hours to their account

### ISSUE THREAD

**Issue by SamR71** [SamR71/Office-Hours#17]

**Comment by rsdexter** [comment]
Edited the title since the "add to schedule" button already exists under the class detail view in search. Currently the button does nothing however.

**Comment by rsdexter** [comment]
Under the class section modal under the class search, there is a "Add" button for each section. This should add all of the office hours of that course to the user's account

**Comment by kd2eom** [comment]
https://stackoverflow.com/questions/16906515/how-can-i-get-the-username-of-the-logged-in-user-in-django

**Comment by kd2eom** [comment]
We can just create a new Model for userClasses where each entry contains a username and a list of classes? We can get the user's username using the code in the stackoverflow link above.

**Comment by kd2eom** [comment]
Details on login/authentication system are here

**Comment by kd2eom** [comment]
https://docs.djangoproject.com/en/3.0/topics/auth/default/#django.contrib.auth.login

**Comment by kd2eom** [comment]
I made a branch https://github.com/SamR71/Office-Hours/tree/issue-17
