### ISSUE TITLE
connect login to backend /database and restrict emails

### ISSUE THREAD

**Issue by kirm99** [SamR71/Office-Hours#26]
connect the log-in form so that it is stored in the database to actually log in. restrict emails when signing up to need to be RPI emails

**Comment by kd2eom** [comment]
To-Do:

- Create user model with name, email, password in Django
- When user logs in or registers on frontend, send POST request to backend with the form data
- Use Python library for password hashing/salting. https://www.vitoshacademy.com/hashing-passwords-in-python/&sa=D&source=hangouts&ust=1582839250215000&usg=AFQjCNEuFCs2Eo_Gzoa3exf3u1COt7E5QA 

- User should get token with session ID when they log in, that token gives them authentication to use certain features of the database. For now, just use a placeholder token like "1". (Full functionality of login system does not need to be finished in this sprint)
